### ISSUE TITLE
.kts build files get red warnings when embedded jdk

### ISSUE THREAD

**Issue by gs-ts** [chrisbanes/tivi#1020]
I am struggling to find out what JDK is the right one in order to have a successful build and .kts files without errors.

Initially, the build failed so I did what was suggested [here](https://github.com/chrisbanes/tivi/issues/954#issuecomment-1260493603), I selected the embedded JDK option (see image below).

<img width="1122" alt="Screenshot 2022-11-30 at 11 36 03 AM" src="https://user-images.githubusercontent.com/12731470/204760277-ff101c6b-24d2-44a7-bff5-35bc8c1bc9f4.png">

Now the build succeeds but all the gradle .kts files are with red warnings (see image below).
 
<img width="1029" alt="Screenshot 2022-11-30 at 11 36 37 AM" src="https://user-images.githubusercontent.com/12731470/204760429-9e604f95-b6ed-4cfd-adb7-2f81a4daebb5.png">

**Comment by chrisbanes** [comment]
The embedded JDK is the right one to use. The errors are more of an Android Studio/IntelliJ bug, than anything I can fix unfortunately.
