### ISSUE TITLE
Main Screen with bottom tab overlapping with same instance!

### ISSUE THREAD

**Issue by ashishbhandari** [chrisbanes/tivi#104]
Steps to reproduce on Samsung devices:

- Launch Application, tap on more of trending or popular
-Tap on bottom library tab , now tap on Discover tab
- Now Press System Back button, I am able to see overlapping of main screen with same instance.

![tivi_bug](https://user-images.githubusercontent.com/578901/34593112-d11b80a0-f1ee-11e7-88a8-7c2c510ff10a.png)

**Comment by chrisbanes** [comment]
I can't reproduce this from master. I'm not sure what build you're using, but the UI in the screenshot is very old. Try re-building.
