### ISSUE TITLE
Migrate from trakt-java

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/tivi#1091]

**Comment by chrisnkrueger** [comment]
I will complete the Trakt library in the following days.
https://github.com/MoviebaseApp/trakt-api.

**Comment by chrisbanes** [comment]
Nice! I'll contribute too once I have a bit more free time later next week.

**Comment by chrisnkrueger** [comment]
I hadn't time to test the API, but I will work end of the week on the trakt-api.
