### ISSUE TITLE
Migrate from tmdb-java

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/tivi#1092]

**Comment by chrisnkrueger** [comment]
I am building up the entire TMDB Api as a KMM library. If you are interested, I can customize the lib according to your expectations.
[https://github.com/MoviebaseApp/tmdb-api](tmdb-api)

**Comment by chrisbanes** [comment]
> @chrisbanes I am building up the entire TMDB API as a KMM library. If you are interested, I can customize the lib according to your expectations. [https://github.com/MoviebaseApp/tmdb-api](tmdb-api)

Nice! Saves me doing it 🎉

**Comment by chrisnkrueger** [comment]
This was fast :) I will check the FIXME comments in your PRs & complete the API a bit more. 

Thanks for your contribution.
