### ISSUE TITLE
Clicks on horizontal lists are ignored when their over-scroll animation is running

### ISSUE THREAD

**Issue by saket** [chrisbanes/tivi#1120]
https://user-images.githubusercontent.com/2387680/219933135-2f637b8d-251e-4d93-b396-e39ff3adfac6.mp4

Noticed this very strange bug today. Touch events made during an over-scroll animation seem to be causing the animation to extend and ignore any clicks from being registered. This can't be specific to tivi, right?

**Comment by chrisbanes** [comment]
I'm not using anything Tivi specific here. I migrated away from Snapper, so this looks like a Compose UI Foundation issue to me

**Comment by saket** [comment]
Thanks for confirming! I filed an issue: https://issuetracker.google.com/issues/269949799.
