### ISSUE TITLE
Can't build the app

### ISSUE THREAD

**Issue by rewgoes** [chrisbanes/tivi#1224]
I've tried to build with Java 11 and 17 and I can't find a way to build it. Can someone please help?

```
Failed building KotlinMPPGradleModel
org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':core:analytics:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:721)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$600(DefaultTaskContainer.java:76)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.domainObjectCreationException(DefaultTaskContainer.java:713)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:948)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.access$1401(DefaultTaskContainer.java:660)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:686)
```

```
Caused by: org.gradle.jvm.toolchain.internal.NoToolchainAvailableException: No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
```

<img width="909" alt="image" src="https://user-images.githubusercontent.com/5007558/235964310-bd554157-358b-4fc3-8e99-9746c1802b89.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/5007558/235964695-96db4ba6-7371-45d6-bda3-d50ebd6e5c4f.png">

**Comment by rewgoes** [comment]
By running that, I got
```
* What went wrong:
Could not determine the dependencies of task ':app:packageQaDebug'.
> Could not create task ':app:compileQaDebugJavaWithJavac'.
   > Failed to calculate the value of task ':app:compileQaDebugJavaWithJavac' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).
```

Following the [link](https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories), I've applied the suggested changes to `settings.gradle.kts` and I was able to compile it. I'm not sure exactly what it does, but by the description of it, it allows using multiple versions of Java in a machine. I'm not sure why I was the only one who needed, and which Java version it decided to use. My environment seems to be set up properly, and if Java 17 was required, it should had worked without the toolchain.

```
Index: settings.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/settings.gradle.kts b/settings.gradle.kts
--- a/settings.gradle.kts	(revision 2e02ff35d13e5bee9a5b9b5d9236c62fa4e7a96b)
+++ b/settings.gradle.kts	(date 1683132274710)
@@ -25,6 +25,7 @@
 
 plugins {
     id("com.gradle.enterprise") version "3.13"
+    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
 }
 
 gradleEnterprise {
```

**Comment by chrisbanes** [comment]
Weird. Maybe I should remove the `toolchain` support and just set the language level's directly. Glad you got it working anyway.

**Comment by erikghonyan** [comment]
@chrisbanes can you run `./gradlew -q javaToolchains` to see if you already have Java 11 installed automatically?

Starting from v8.0 Gradle [will no longer auto-download the Java toolchain if no repositories are configured](https://docs.gradle.org/8.0.2/userguide/upgrading_version_7.html#using_automatic_toolchain_downloading_without_having_a_repository_configured), which it looks like the Tivi app doesn't do, unless I missed it. One way to do this is to [apply the Disco Toolchains Plugin](https://docs.gradle.org/current/userguide/toolchains.html#sub:download_repositories)

**Comment by chrisbanes** [comment]
I have JDK 11 and 17 installed locally. I don't personally like the autoinstalling toolchains tbh.

**Comment by erikghonyan** [comment]
Yeah that's fair enough 🙂 @rewgoes can you please also run that Gradle command to check if Gradle sees your Java 11 installation?

**Comment by rewgoes** [comment]
As I already got the app working/building before, I decided to start the project with a fresh clone of the repo and after cleaning all my gradle cache. Before adding the Disco Toolschains Plugin, I got the following Javas:
 + JetBrains s.r.o. JDK 17.0.6+0-17.0.6b802.4-9586694
 + OpenJDK 20.0.1+9-29

I was unable to sync the project with those Java versions

After adding the plugin, it downloaded a version of Java 11, and the app synced successfully. 
 + Eclipse Temurin JDK 11.0.19+7

**Comment by chrisbanes** [comment]
Closing this as it's mostly a setup issue.

**Comment by dilraj-singh1997** [comment]
Seems like the distribution for toolchain management does not exist for apple- https://github.com/gradle/foojay-toolchains
![image](https://github.com/chrisbanes/tivi/assets/87430699/114eee9b-8270-4a6b-976f-a780309c51d9)

**Comment by erikghonyan** [comment]
@dilraj-singh1997 the Foojay Toolchains plugin is not applied in this repo and no vendor is specified. Can you please elaborate on your comment?

**Comment by chrisbanes** [comment]
Also, Apple here means the 'official' JDK built by Apple (which is no longer supported). Azul and Temurin work fine on Mac.

**Comment by dilraj-singh1997** [comment]
I tried adding `id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"` to build.gradle file as mentioned previously, but it was not working on my MacBook. Anyways I got it working on my other laptop by using the same fix.

**Comment by sevar83** [comment]
Had the same issue on Windows 11 although I've tried multiple JDKs (11, 17, 20, the Studio built-in one) and setting JAVA_HOME to point to the correct JDK but for some reason the auto-detection fails. I've managed to get it working by adding Foojay resolver to `build-logic/build.gradle`.
