### ISSUE TITLE
Use Gradle convention plugins to share build logic

### ISSUE THREAD

**Issue by erikghonyan** [chrisbanes/tivi#1243]
Tivi Gradle modules share some common build logic. This is either done by duplicating it in every module (e.g. applying the cache fix plugin) or using the `allprojects` block.

Gradle's recommended way to do this is to use [convention plugins](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html). The idea is to have plugins like `app.tivi.android.library`, `app.tivi.android.application` (and apply these instead of the `com.android.library` and `com.android.application`). These plugins can then configure the common build logic. If needed, the modules can override these defaults (which is trickier to do with the `allprojects` block).

One downside with this approach is that you might forget to apply the convention plugins and use the standard Android plugins instead. If this is really an issue, the `allprojects` block can be used to check that every module applies one of the convention plugins.

Here are a few examples using it
https://github.com/android/nowinandroid/tree/main/build-logic
https://github.com/dropbox/focus/blob/main/settings.gradle#L2
https://github.com/jjohannes/gradle-project-setup-howto/blob/main/settings.gradle.kts#L2

**Comment by erikghonyan** [comment]
Great! 🎉 If you agree with this approach I'd be more than happy to contribute!

**Comment by chrisbanes** [comment]
Yeah, any help is greatly appreciated!
