### ISSUE TITLE
Cover art not loaded when loading for the first time

### ISSUE THREAD

**Issue by tom-bell** [chrisbanes/tivi#1465]
Opening app version 0.9.3 for the first time the cover art is not available until you scroll, and only new content has art loaded. See screenshots.

Thanks for the great app and work!

![Screenshot_20230817-175331.png](https://github.com/chrisbanes/tivi/assets/514507/0f08daf9-93f3-433b-ae30-14fcf8c63eab)

![Screenshot_20230817-175322.png](https://github.com/chrisbanes/tivi/assets/514507/1e708953-ce25-4ae0-8aed-b8640d576396)

**Comment by chrisbanes** [comment]
Thanks for the report. I think this might be a migration issue from Coil -> the KMP Image Loader.

Do the images load if you clear the app's cache?
