### ISSUE TITLE
Support showing licenses in About page

### ISSUE THREAD

**Issue by Goooler** [chrisbanes/tivi#1471]
We can use [Licensee](https://github.com/cashapp/licensee) to generate a dependency report and show it in About page.

**Comment by chrisbanes** [comment]
PRs welcome here! Licensee will generate the JSON file, but off the top of my head we'll need:

- [ ] Gradle task to copy the JSON file into the generated resources folder
- [ ] JSON parsing of the file
- [ ] UI to display
- [ ] Make it work across the different variants (and platforms)

**Comment by penkzhou** [comment]
I just create a pr for the issue.
https://github.com/chrisbanes/tivi/pull/1528
