### ISSUE TITLE
An option to auto ignore specials

### ISSUE THREAD

**Issue by Stanzilla** [chrisbanes/tivi#1487]
Hey there! Would be nice if there was an option to auto ignore the specials season on every show

**Comment by chrisbanes** [comment]
What's do you see as the benefit of ignoring specials? At the moment the only difference would be that they are greyed out in the list.

**Comment by Stanzilla** [comment]
> What's do you see as the benefit of ignoring specials? At the moment the only difference would be that they are greyed out in the list.

I have many shows that have episodes listed as "to watch" which are only the specials, which I usually don't watch.

**Comment by chrisbanes** [comment]
Hmmm. Specials should be explicitly removed from those lists (hardcoded into the SQL iirc) but maybe something has regressed.

I agree though, this is a more 'generic' way to handle this.

**Comment by Stanzilla** [comment]
> Hmmm. Specials should be explicitly removed from those lists (hardcoded into the SQL iirc) but maybe something has regressed.
> 
> I agree though, this is a more 'generic' way to handle this.

I'm not ruling out the possibility of me just being confused, I'll double check! And thank you :)

**Comment by chrisbanes** [comment]
Hmmm. Would you mind attaching a screenshot? I'm interesting in seeing which shows are triggering this.

I don't see any shows with specials in my 'Up Next' list.

**Comment by chrisbanes** [comment]
Just looked a bit more into this. We use a SQL view underneath which explicitly ignores 'specials' (which use a season number of `0`) [here](https://github.com/chrisbanes/tivi/blob/main/data/db-sqldelight/src/commonMain/sqldelight/app/tivi/data/shows_next_to_watch.sq#L11). I'm wondering if there's something weird going on with certain shows.

**Comment by Stanzilla** [comment]
> Just looked a bit more into this. We use a SQL view underneath which explicitly ignores 'specials' (which use a season number of `0`) [here](https://github.com/chrisbanes/tivi/blob/main/data/db-sqldelight/src/commonMain/sqldelight/app/tivi/data/shows_next_to_watch.sq?rgh-link-date=2023-08-27T09%3A41%3A33Z#L11). I'm wondering if there's something weird going on with certain shows.

They were not in the up next list, it just showed up as "N unwatched" in the list but now I can't find one anymore because I went through and hit ignore on all of the season 0s :/ I guess this can be closed and I can come back when it happens again
