### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Suburbanno** [chrisbanes/tivi#1504]
Hello!

Thank you for your amazing App.

Do you already have something in mind to support translations? there are platforms that facilitate this, such as Crowdin, Transifex and others.

**Comment by Suburbanno** [comment]
@chrisbanes Do you have something in mind about this?

**Comment by chrisbanes** [comment]
I’m looking into using Crowdin at the moment. 

This will require some changes to how we handle strings in the app first though. At the moment we use Lyricist, which are hand written strings in a Kotlin class. That won’t work for Crowdin, so we need to migrate to something declarative.

**Comment by chrisnkrueger** [comment]
@chrisbanes Multiplatform Compose has an alpha plugin for resources
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html
