### ISSUE TITLE
A documentation/blog to understand this advanced code

### ISSUE THREAD

**Issue by vipulasri** [chrisbanes/tivi#151]
I would request you to please add a documentation/write a blog so that developers can understand and learn from your advance code. 
It would be really helpful.

**Comment by shakil807g** [comment]
yes agree with @vipulasri  please add a documentation/write a blog  about the Architecture followed in this project (e.g multi modules )

**Comment by AbdulDroid** [comment]
@vipulasri and @shakil807g you can start from here
- https://fernandocejas.com/2014/09/03/architecting-android-the-clean-way/ or 
- https://medium.com/google-developer-experts/modularizing-android-applications-9e2d18f244a0
I hope this help you better understand this project structure

**Comment by vipulasri** [comment]
@AbdulDroid Thanks for the links but what I am actually talking about is the modularity of the code not the modularity at the project level.
