### ISSUE TITLE
Publish beta of iOS app to TestFlight

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/tivi#1534]
We're very nearly at the point of publishing a public beta of the iOS app. This is just a tracking bug.

If you're interesting in testing this, feel free to subscribe to this issue and I'll post instructions when it's ready.

**Comment by pablichjenkov** [comment]
+1

**Comment by chrisbanes** [comment]
First beta build is now available on TestFlight: https://testflight.apple.com/join/6eCvykFA

Feedback welcome!

**Comment by pablichjenkov** [comment]
When access the link it redirects to test flight App with an alert saying:
"Tivi App is full"

**Comment by chrisbanes** [comment]
I’ve just opened up another bunch of testing slots at the same link

**Comment by StylianosGakis** [comment]
It seems to be full again. But it may also be that you don't want to infinitely make more and more slots as more people are asking for it. In any case, if you do end up making more slots, I would be happy to be notified in this thread so I can also give it a shot 😊

**Comment by chrisbanes** [comment]
I've increased the limit to 500, so we should be good for a while now
