### ISSUE TITLE
How to perform oauth PKCE flow on Kotlin multiplatform

### ISSUE THREAD

**Issue by clarkshu1016** [chrisbanes/tivi#1773]
before the code used https://github.com/openid/AppAuth-Android library to perform oauth pkce flow ,now project updated to kotiln multiplatform,did still use this AppAuth-Android ? seems not, so how to perform oauth pkce flow on kotlin multiplatform with ktor?

**Comment by chrisbanes** [comment]
This isn't a development question and answer forum. Not sure why you thought to post here?
