### ISSUE TITLE
Inconsistent windows inset top (or details_status_bar_anchor height) in ShowDetailsFragment

### ISSUE THREAD

**Issue by eneim** [chrisbanes/tivi#201]
Please take a look at this gif first and focus on the top notch where the Toolbar is drawn, before and after the animation:

![img_3182](https://user-images.githubusercontent.com/1776230/44324202-d8d64600-a48f-11e8-8956-7806c478f993.gif)

As you can see, right after opening the detail for Bigbang Theory, the inset top is correctly set (details_status_bar_anchor height is equal to the height of top notch in this device),

After I scroll it, somehow this height is reset to default (24dp) and it results in that the toolbar is cut by the top notch.

Device detail: LG G7 (Android 8.0, so no DisplayCutout yet, but windows insets are correctly set).

Below are some (hopefully) useful log screenshot

> ShowDetailsFragment#onViewCreated

<img width="480" alt="screen shot 2018-08-20 at 15 33 00" src="https://user-images.githubusercontent.com/1776230/44324341-58fcab80-a490-11e8-8c95-9e48250c9a9d.png">

<img width="480" alt="screen shot 2018-08-20 at 15 33 14" src="https://user-images.githubusercontent.com/1776230/44324377-72055c80-a490-11e8-88f2-8562eafe3b81.png">

> Scroll up and observe the onLayout in TintingToolbar (I override this method for debugging only)

<img width="480" alt="screen shot 2018-08-20 at 15 33 36" src="https://user-images.githubusercontent.com/1776230/44324395-7fbae200-a490-11e8-8739-84556ceb953c.png">

**Comment by chrisbanes** [comment]
See https://github.com/chrisbanes/tivi/blob/master/app/src/main/res/layout/fragment_show_details.xml#L121

KI in MotionLayout: https://issuetracker.google.com/issues/112605433

**Comment by eneim** [comment]
@chrisbanes Oh, I thought that line is the indicator for [this work](https://github.com/chrisbanes/tivi/blob/master/app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt#L78) already. Gotta wait!

**Comment by chrisbanes** [comment]
Fixed in #269
