### ISSUE TITLE
Static code analyzer

### ISSUE THREAD

**Issue by samarjan92** [chrisbanes/tivi#24]
Why was the ktlint chosen as the static code analyzer? What's about another  more powerful tool like detekt?

**Comment by chrisbanes** [comment]
Ktlint isn't really a static code analyser, it's a code style checker similar to checkstyle. That is the only purpose for which I integrated it.

I wasn't aware of Detekt, so thanks for the heads up.

**Comment by chrisbanes** [comment]
Going to close this since ktlint is working great.
