### ISSUE TITLE
Please Provide some design flow or how app works with some diagram or blog

### ISSUE THREAD

**Issue by TheReprator** [chrisbanes/tivi#267]
First of all, thanks for this project and I am a great admirer of your work.

I am making my effort to go through the code by putting the debugger at every line of project but hadn't achieved any success so far but certainly, I will.

It would be great if you can provide some description or diagram how the app is working or to whom it is interacting, it will be a great benefit for others like me like this buffer app(https://github.com/bufferapp/android-clean-architecture-boilerplate)

I had gone through the same issue #151 but still I was unable to understand the app interaction.

I hope I will listen very shortly, from you guys.

**Comment by amrro** [comment]
If you are getting hard time reading the code in different modules, You could try refactoring the project and build a similar project with different API or add another feature to the project using trakt or tomb's APIs.
Try Also to acquaint yourself more with the libraries used in the project like `MvRx` and `Epoxy` for example.
I started digging into this project this week; I am using pen and paper to takes notes and draw how the data flow from the API to be cached then how it reach UI to be populated.

**Comment by TheReprator** [comment]
@amrro thanks for suggestion, till now I am also making notes to know the flow, still it would be a great benefit it, some references is there.

**Comment by amrro** [comment]
Hey @TheReprator, 
I found this it might benefit you
![MVVMi](https://cdn-images-1.medium.com/max/2400/1*on-ikVa_TGT8d_hP5Xts9g.jpeg)

**Comment by shoteroaryan** [comment]
Can anyone help me get set up? I am getting the AndroidRuntime: FATAL EXCEPTION: main error. 

java.lang.NoSuchMethodError: No static method copy$default
