### ISSUE TITLE
Suspicious Line of Code: API Call Max Retries Count

### ISSUE THREAD

**Issue by nick-morhun** [chrisbanes/tivi#287]
The code line is here: [line](https://github.com/chrisbanes/tivi/blob/865eadfed09c1336ffa446a6a7c72cfe7f1b6103/base/src/main/java/app/tivi/extensions/RetrofitExtensions.kt#L40)

The whole fragment is this:

```
repeat(maxAttempts - 1) { attempt ->
    try {
        // Clone a new ready call if needed
        val call = if (isExecuted) clone() else this
        return call.execute()
    } catch (e: Exception) {
        // The response failed, so lets see if we should retry again
        if (attempt == (maxAttempts - 1) || !shouldRetry(e)) {
            throw e
        }
    }
    // Delay to implement exp. backoff
    delay(nextDelay)
    // Increase the next delay
    nextDelay *= 2
}

// We should never hit here
throw IllegalStateException("Unknown exception from executeWithRetry")
```

For example, when the server is not responding, `attempt == (maxAttempts - 1)` will never be true and this code always hits the last line.
When it is changed to repeat `maxAttempts` times, it throws the timeout exception after the 3rd time as it should.

**Comment by chrisbanes** [comment]
Woops, thanks for the catch! Good work 🕵️
