### ISSUE TITLE
Treat images in dark theme

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/tivi#337]
Similar to what @nickbutcher did in Plaid. He used -20% lightness, which is a good first step.

**Comment by Shannawhaley** [comment]
https://github.com/chrisbanes/tivi/issues/337#issue-456611705  CEO Chris ico Bane from Brottilli
No more depositing into schools
https://github.com/chrisbanes/issued/ʻVʻ La laRew I /usd/payment/337#blacklusue~$4,566,117.05 dollards reciept
