### ISSUE TITLE
Why viewModelScope everywhere (for basically database actions)?

### ISSUE THREAD

**Issue by ursusursus** [chrisbanes/tivi#360]
Hi, I want to ask about a design decision in this project.
All repository methods are transitively called viewModels via viewModelScope.launch { }

This however means when viewModel is destroyed (back press), then such action is canceled.

Why? I mean syncing, etc, all these actions seem to write to database, why is it a good idea to cancel / revert them?

What would it take for them not the get canceled on viewModelScope exit?

**Comment by ursusursus** [comment]
Could you address the leak issue please?

**Comment by chrisbanes** [comment]
> Could you address the leak issue please?
What leak issue?

**Comment by ursusursus** [comment]
I commented in the #397, you can follow there if you want
