### ISSUE TITLE
This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.

### ISSUE THREAD

**Issue by davran312** [chrisbanes/tivi#371]
Hi there. I have tried to compile your project but, i faced with many problems with trying it .
After some time with fixing .  I get - This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer. 
I tried to up gradle version . Updated my android studio to the latest version . But i actually can not build and run it )

**Comment by chrisbanes** [comment]
Hi, you need to use [Android Studio 3.5](https://developer.android.com/studio/preview) which is currently at RC
