### ISSUE TITLE
Add test apk to the releases

### ISSUE THREAD

**Issue by TheCodingWarlock** [chrisbanes/tivi#391]
Is there a way to test the app without building the project? A link to the final APK in the README would be great. I hit a memory issue while building the APK but I'd like to see how the app looks like. Thank you

**Comment by shakil807g** [comment]
https://drive.google.com/open?id=16UxO_I2wYLufyZpddVZM636pLq6-f8WQ

**Comment by TheCodingWarlock** [comment]
Is the link updated with the latest APK and is it safe?

**Comment by chrisbanes** [comment]
I'm gearing up for an alpha release very soon.

Before that though, I think tagging releases on GitHub is a good idea (with APKs). Reminder to myself, follow this [blog post](https://circleci.com/blog/publishing-to-github-releases-via-circleci/).

**Comment by chrisbanes** [comment]
[v0.2.30](https://github.com/chrisbanes/tivi/releases/tag/v0.2.30) is now up on the releases page with APKs. These are automatically built and deployed from the CI server.
