### ISSUE TITLE
I'd like to give a hand - here is a question

### ISSUE THREAD

**Issue by mitrejcevski** [chrisbanes/tivi#4]
I've spotted some places like the `HomeActivity` having variables defined as nullable, f.e
```private var viewModel: HomeActivityViewModel? = null```
Is there a reason behind it? I think they could be made `lateinit` vars and avoid the nullability.
I'd be glad to give a hand in the project, so I'd be glad if you could give some insight about this approach. Cheers!

**Comment by chrisbanes** [comment]
Yeah I think you're right about `lateinit` 👍.

This app is my playground to learn Kotlin, and I'm still learning.
