### ISSUE TITLE
Images flickering until cached

### ISSUE THREAD

**Issue by lineargs** [chrisbanes/tivi#432]
Once opened details for any show the images starting to flicker once scrolling down. The issue happens every time the app is reopened. Once the images are cached the issue disappears.

Once the Related shows images are cached the issue do not exists.

Device: Google Pixel XL
Android version: 9
Build number: PQ3A.190801.002

Device: Google Pixel XL
Android version: 10
Build number: QPP6.190730.005

![20190825_085344_2 2019-08-25 09_36_02](https://user-images.githubusercontent.com/3036412/63647614-c97d7e80-c71b-11e9-95d6-17dc6ea66b2b.gif)

**Comment by chrisbanes** [comment]
Thanks! I think this is fixed in #424, which I've just pushed out in v0.3.1. Let me know if you still see this after the update.

**Comment by lineargs** [comment]
Thanks, this is resolved.
