### ISSUE TITLE
Images in the Discover screen sometimes don't load

### ISSUE THREAD

**Issue by Kernald** [chrisbanes/tivi#437]
I found an interesting pattern: when I open the app (cold start), everything loads fine. I then switch to Followed, open the sorting menu (that's important, everything works fine if I don't do that, I tried ~10 times both cases, and got consistent results every single time), don't change anything in the sorting menu, close it and switch back to Discover. The "Keep watching" episode is displayed without a poster (not even a placeholder, it's totally blank), and the two first (once again, it's consistent) shows in "Recommended for you" are not loading either (there's a placeholder this time though).

**Comment by chrisbanes** [comment]
I *think* this is fixed by my move to Coil, at least I haven't seen it since migrating. I'm going to close this for now, if you see this in the next release (should be out tomorrow) please comment and I'll re-open.
