### ISSUE TITLE
Regarding the application set up 

### ISSUE THREAD

**Issue by AbhiAndroidManiac** [chrisbanes/tivi#458]
I did the same but the build got failed on several ocassions.  API 'variant.getPreBuild()' is obsolete and has been replaced with 'variant.getPreBuildProvider()'.
 and API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
 these are the error I am getting while setting up the project on the android studio. The methods are deprecated and The line where this error are being thrown are not being located.

**Comment by chrisbanes** [comment]
That is just a warning, the build will still work.
