### ISSUE TITLE
Possible crash using PagedList in FollowedViewState MvRxState?

### ISSUE THREAD

**Issue by VGJohn** [chrisbanes/tivi#468]
Since PagedList is mutable won't this cause issues with MvRxState which expects immutable state? Curious how you're avoiding this problem.

**Comment by chrisbanes** [comment]
I'm not at the moment but it is something I'm aware of. Luckily it hasn't caused any issues in release. It does very rarely crash in debug mode, due to MvRx's immutable state checks though.

**Comment by VGJohn** [comment]
I see, I'm hitting more consistent crashes in debug mode due to this issue, was hoping you had some sort of workaround. Looks like I'll have to exclude it from the MvRxState and direct it into the PagedListEpoxyController using LiveData for now. Thanks though!

**Comment by chrisbanes** [comment]
This is probably worth a discussion with the MvRx folks though. Would be good if there was a way to make a piece of state as transient.

**Comment by VGJohn** [comment]
Sure I'll bring it up with them and comment back here if I learn anything more. I did see some old issues in their backlog asking about using PagedList within the MvRxState that didn't get much attention so I'm not expecting much feedback. Cheers.
