### ISSUE TITLE
HomeFragmentViewModel hold HomeActivity reference

### ISSUE THREAD

**Issue by baoti** [chrisbanes/tivi#47]
`HomeFragmentViewModel` is retained after screen rotated and `HomeActivity` recreated.
But `HomeFragmentViewModel` still hold old `HomeNavigator` (also`HomeActivity`) instance.

**Comment by chrisbanes** [comment]
Good catch.

**Comment by chrisbanes** [comment]
I've investigated this and what you described does not happen. Each fragment will get a new ViewModel created for it, which in turn gets the correct `HomeNavigator`.

Do you have any reproduction steps?

**Comment by chrisbanes** [comment]
OK, I lied. I was not seeing the issue due to #60, so a new fragment was being created every time. Fixing now.
