### ISSUE TITLE
Toolbar title disappears on screen rotation

### ISSUE THREAD

**Issue by manueldidonna** [chrisbanes/tivi#483]
Version 3.6

- rotate the screen
- toolbar title becames blank
- swap between tabs, nothing change
- open settings
If I press back button, the toolbar title became "settings". If I click on the same tab, settings disappears and the toolbar has a blank title again

**Comment by manueldidonna** [comment]
This issue seems to be fixed with version 3.6.1

**Comment by chrisbanes** [comment]
Yep, I forgot to reference this issue. Was fixed in #488
