### ISSUE TITLE
Duplicate dependencies question

### ISSUE THREAD

**Issue by tomislavhofman** [chrisbanes/tivi#491]
What is the reason behind duplicating dependencies in gradle files?

Example

> :base:build.gradle
> `api Libs.Coroutines.core`

> :app:build.gradle 
> `implementation project(":base")`
> `...`
> `implementation Libs.Coroutines.core`

There are many more to be found, so it makes me think it's not accidental.

**Comment by chrisbanes** [comment]
Actually completely accidental. I need to go through and sanitize the module dependencies
