### ISSUE TITLE
Wrong images are loaded while scrolling down and the next page loads

### ISSUE THREAD

**Issue by VGJohn** [chrisbanes/tivi#492]
My connection isn't the best so it takes some time for the images to load. If I fling the list down causing it to stop while another page loads then the incorrect images are loaded for each show for a few seconds. You can see in the screenshots that some duplicates show first, then completely incorrect images for each show until it finally loads in the correct images. This occurs in version 3.6.2

![Screenshot_20191012-091211_Tivi debug](https://user-images.githubusercontent.com/22520267/66697823-048a4000-ecd1-11e9-9902-749352bbc4b0.jpg)
![Screenshot_20191012-091219_Tivi debug](https://user-images.githubusercontent.com/22520267/66697835-153ab600-ecd1-11e9-83ca-7d59b965b051.jpg)
![Screenshot_20191012-091225_Tivi debug](https://user-images.githubusercontent.com/22520267/66697843-25529580-ecd1-11e9-84ce-d66bd2e7fb7b.jpg)

**Comment by chrisbanes** [comment]
Thanks for the report. This has been a long standing issue, which I still haven't been able to track down the root cause of.

The commit linked above may finally fix it.

**Comment by VGJohn** [comment]
@chrisbanes just wanted to confirm in v0.4 that this has been fixed! Nicely done!
