### ISSUE TITLE
MvRx mutable state app crash on v0.4 debug

### ISSUE THREAD

**Issue by VGJohn** [chrisbanes/tivi#517]
Getting an app crash from MvRx saying the immutable state was mutated on the debug build. It occurs consistently when I scroll down quite quickly through the discover shows list. Crash log attached.

Device: Samsung S10+ Android 9

[tivi-app-crash-log.txt](https://github.com/chrisbanes/tivi/files/3826755/tivi-app-crash-log.txt)

**Comment by chrisbanes** [comment]
This is due to https://github.com/airbnb/MvRx/issues/290. I've asked the MvRx devs about that issue so hopefully we'll see some movement soon.
