### ISSUE TITLE
Typo in file name "delgates.kt" instead of "delegates.kt"

### ISSUE THREAD

**Issue by itsandreramon** [chrisbanes/tivi#549]
https://github.com/chrisbanes/tivi/blob/master/base/src/main/java/app/tivi/extensions/delgates.kt

This file should be renamed to "delegates.kt" or "Delegates.kt"

**Comment by Scienticious** [comment]
@chrisbanes may I fix this issue?

**Comment by chrisbanes** [comment]
Sure, please do!
