### ISSUE TITLE
Application graph. 

### ISSUE THREAD

**Issue by AbhiAndroidManiac** [chrisbanes/tivi#565]
Hello, is it possible to share application graph. Its more of a request.

**Comment by chrisbanes** [comment]
What's an 'application graph'?

**Comment by AbhiAndroidManiac** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/36920235/75546590-dd999400-5a4e-11ea-8ea8-15fdf57d4dbe.png)

As google defines it just displays the graph of the scope of the dagger dependency.

**Comment by chrisbanes** [comment]
I have no plans to create and maintain one of these unfortunately.

**Comment by AbhiAndroidManiac** [comment]
Ok, it is just for understanding the code better. No problem. Thanks for the quality code.
