### ISSUE TITLE
The Project is incompatible version of Android Gradle Plugin

### ISSUE THREAD

**Issue by Scienticious** [chrisbanes/tivi#566]
![Screenshot from 2020-03-01 18-15-13](https://user-images.githubusercontent.com/11726108/75626366-e6be6880-5be8-11ea-83d8-18e71420d012.png)

Unable to open project, any idea what am I doing wrong?

**Comment by AbhiAndroidManiac** [comment]
Change the gradle version in the project gradle file to current version of your android studio. I think the latest it might be 3.5.3

**Comment by chrisbanes** [comment]
This project is currently built for Android Studio 3.6.x. Update your Android Studio and it should work fine

**Comment by Scienticious** [comment]
I am using the latest version (3.6.1), I want to contribute in this project.
Is there any way to run this project.
When I click on Update button it showing that error
<img width="1677" alt="issue github" src="https://user-images.githubusercontent.com/11726108/76079501-9408f600-5fc6-11ea-97e5-ec6828b5efed.png">

**Comment by ermanishks** [comment]
Build error  :: "The project is using an incompatible version (4.1.0-alpha09) of the Android Gradle plugin."

I am using android studio 4.1  canary 10
