### ISSUE TITLE
Seeing missing images on the more screens

### ISSUE THREAD

**Issue by yschimke** [chrisbanes/tivi#597]
Haven't been able to work out where these are coming from, not seeing failed requests etc.

Reporting, but it might just be me.  Happens if I scroll through the more screens very quickly.

**Comment by yschimke** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/231923/80871413-59f56100-8ca4-11ea-9b7a-2644b63cb766.png">

**Comment by yschimke** [comment]
Not sure if related but got into this state with images

<img width="397" alt="image" src="https://user-images.githubusercontent.com/231923/81401840-10839680-9128-11ea-900c-908e7b6c9835.png">

**Comment by chrisbanes** [comment]
Weird, that looks like a shared element transition gone wrong. Or maybe RecyclerView's item animator going a being weird.

**Comment by chrisbanes** [comment]
Hopefully this is now fixed, now that we've moved to Compose.
