### ISSUE TITLE
Included in F-Droid

### ISSUE THREAD

**Issue by tgp1994** [chrisbanes/tivi#610]
It would be great to see this project [included](https://f-droid.org/en/docs/Inclusion_How-To/)  in the F-Droid repository. Among other things, this would make Tivi more accessible, you can show off screenshots of the app, and test versions can be quickly deployed.

**Comment by chrisbanes** [comment]
I don't think that this is going to work. There are a number of 'secrets' (client IDs, API keys, etc) which are part of the GitHub Actions build, and not committed to the source repo.

**Comment by Poussinou** [comment]
@chrisbanes Would it be possible to attach the apk in the [release] section with each new tag please?

**Comment by alexanderadam** [comment]
> There are a number of 'secrets' (client IDs, API keys, etc) which are part of the GitHub Actions build, and not committed to the source repo.

Other apps give users the possibility to add own API keys in the settings.
Wouldn't this be a possibility here as well? :thinking:

**Comment by chrisbanes** [comment]
> Other apps give users the possibility to add own API keys in the settings. Wouldn't this be a possibility here as well? 🤔

PRs welcome!

**Comment by alexanderadam** [comment]
Oh, in case you're open to such a solution it would make sense to reopen this issue, doesn't it?
This would likely increase the possibility that someone knowing Kotlin would find this issue.

What do you think?

**Comment by chrisbanes** [comment]
Probably better to open a new issue. This is about pushing F-Droid, not the ability to set your own API keys

**Comment by IzzySoft** [comment]
Is there any chance for a more detailed description (what about the app offers, what to expect from it), and maybe some screenshots? While the API key requirement and Firebase are show-stoppers for F-Droid.org, your app might qualify for [my repo](https://apt.izzysoft.de/fdroid) until it's ready to meet F-Droid's stronger criteria. Inclusion with my repo [was even requested](https://gitlab.com/IzzyOnDroid/repo/-/issues/266) already.
