### ISSUE TITLE
Gradle sync failed: Unsupported method: AndroidArtifact.getBuildConfigFields()

### ISSUE THREAD

**Issue by hotmule** [chrisbanes/tivi#616]
I'm trying to build your project, but still getting this error, tried different versions of Gradle Plugin and Version, but nothing seems to work

**Comment by chrisbanes** [comment]
The app is green on CI and building fine for me locally. The app depends on the latest AGP 4.1.0 alpha (current 09) and can't be built with earlier versions.

**Comment by hotmule** [comment]
Weird thing, maybe it is AS Cannary bug

**Comment by chrisbanes** [comment]
Are you using Android Studio 4.1 Canary 9?

**Comment by hotmule** [comment]
Oh, seems like I used outdated version, Snap Store provides Canary build from 6 March 2020
