### ISSUE TITLE
Build failed: Extension not initialized yet error

### ISSUE THREAD

**Issue by NaturallyAsh** [chrisbanes/tivi#635]
Hello.  I am having trouble building the app.  The source of the problem, I believe, is coming from the tivi-master/app/build.gradle file.  I get an error (Extension not initialized yet, couldn't access compileSdkVersion) from line 62 (compileSdkVersion buildConfig.compileSdk). The buildscript in the tivi-master/build.gradle file calls for ext.buildConfig to be equal to the sdks, and for some reason the "ext" has not yet been initialized. I apologize but I am unsure of what to do.  The app worked fine for me a few weeks ago.  AS is running Gradle 4.1.0-beta01.  Thank you!

**Comment by chrisbanes** [comment]
Hi, Jetpack Compose (which Tivi uses) only currently works on Android Studio Canary builds. I'm currently stuck on 4.1.0-alpha10 (Canary 10) because of an incompatibility with certain plugins.

Therefore Tivi only currently works with Android Studio Canary 10.

**Comment by NaturallyAsh** [comment]
Alright, I will try to build it with that version.  Thank you!
