### ISSUE TITLE
WorkManager needs to be fixed

### ISSUE THREAD

**Issue by prudhvir3ddy** [chrisbanes/tivi#650]
Hey @chrisbanes just following your hilt commit and realised 

you implemented Configuration.Provider in your application class.

i guess you need to remove the default worker initialisation in manifest file. 

confirm it and i'll send a PR

**Comment by chrisbanes** [comment]
Hi, this should already be done:

https://github.com/chrisbanes/tivi/blob/main/tasks/src/main/AndroidManifest.xml#L25

Thanks though!
