### ISSUE TITLE
How do I navigate to a fragment which accept arguments?

### ISSUE THREAD

**Issue by sudansh** [chrisbanes/tivi#657]
Since the navigation files are in `app` module, feature modules won't have access to the `Args` file. Is there any workaround for that?

example: if I have a fragment which accepts email and password like so
```
<fragment
        android:id="@+id/navigation_sample"
        android:name="SampleFragment">
        <argument
            android:name="email"
            app:argType="string" />
        <argument
            android:name="password"
            app:argType="string" />
    </fragment>
```
I would have a SampleFragmentArgs generated which could be used to navigate
`findnavController.navigate(R.id.navigation_sample, SampleFragmentArgs(email, password).toBundle)`

But I can use this only from `app` module not in a feature module

**Comment by chrisbanes** [comment]
This isn't a development forum for asking questions.
