### ISSUE TITLE
Migrate to "Proto DataStore" new jetpack library

### ISSUE THREAD

**Issue by Abdktefane** [chrisbanes/tivi#698]
this new library is awesome , it's give you strongly typed data (backed by protocol buffers), they are faster, smaller, simpler, and less ambiguous than XML and other similar data formats, Data is stored asynchronously.
i'm working on it and it almost ready , but i notices that `PreferenceFragmentCompat` class is used to build settings UI.
what should i do ? build a new UI for it in xml ? maybe new UI settings in compoes ? or you don't want to migrate at all ?

**Comment by chrisbanes** [comment]
Hmm, you should be able to set the datastore on the PreferenceManager [`PreferenceManager.setPreferenceDataStore`](https://developer.android.com/reference/androidx/preference/PreferenceManager#setPreferenceDataStore(androidx.preference.PreferenceDataStore))

**Comment by chrisbanes** [comment]
I don't plan on using `DataStore` as there's little benefit in Tivi.
