### ISSUE TITLE
Text overlapping over icon in follow show FAB 

### ISSUE THREAD

**Issue by Abdktefane** [chrisbanes/tivi#701]
why this happen ? even the box in `ExpandableFloatingActionButton` has start padding `12.dp`
`Box(Modifier.padding(start = 12.dp, end = 20.dp)) {
                    text()
                }`

![photo_2020-09-23_13-12-01](https://user-images.githubusercontent.com/48357717/94001167-cf231900-fda0-11ea-931c-b8b2b9377c72.jpg)

**Comment by chrisbanes** [comment]
This looks like a bug in `AnimatedVisibility`
