### ISSUE TITLE
SubjectInteractor and StateFlow

### ISSUE THREAD

**Issue by ochkarik05** [chrisbanes/tivi#721]
Trying to understand how SubjectInteractor is expecting to work, especially with `<Unit>` as a parameter. There is even an extension for this:

`operator fun Interactor<Unit>.invoke() = invoke(Unit)`

SubjectInteractor uses a MutableStateflow under the hood, and I wonder if it's a correct way of doing this. For example, when I need to call invoke() several times to trigger a new flow. Or calling invoke() without parameters is a wrong way of triggering new flow?

**Comment by chrisbanes** [comment]
Yep, you're right. Fixed by moving to the new `SharedFlow` instead, which has the same characteristics as a `BroadcastChannel`
