### ISSUE TITLE
Add notification system

### ISSUE THREAD

**Issue by davidegavio** [chrisbanes/tivi#728]
Could be nice if there is a notification system for upcoming series/episodes.
Some possible notifications could be:

- Episode/season release date
- Episode/season coming out in 1 month/week/day
- Episode/serie airs today
All upcoming events could be regrouped in a single view

**Comment by gouri-panda** [comment]
@chrisbanes Can I contribute this?

**Comment by chrisbanes** [comment]
@gouri-panda please do!
