### ISSUE TITLE
UI Discover More > EntryGridFragment > layout_height >  AppBar

### ISSUE THREAD

**Issue by phillipsk** [chrisbanes/tivi#732]
While on the Discover screen clicking More next to Being Watched Now, the layout from EntryGridFragment loads and eclipses the AppBar layout height. See the attached image and the eclipsed AppBar '<- Being Watched Now'

Possible solutions I have reviewed, adjusting the logic around it.height or the setProgressViewOffset within the EntryGridFragment code or within the fragment's layout instead by adjusting the AppBar             `android:layout_height="wrap_content"` to  ` android:layout_height="72dp"`

`        binding.gridAppbar.doOnSizeChange {
            binding.gridRecyclerview.updatePadding(top = it.height)
            binding.gridSwipeRefresh.setProgressViewOffset(
                true,
                0,
                it.height + binding.gridSwipeRefresh.progressCircleDiameter / 2
            )
            true
        }
`

![Screenshot_20201113-113500_Tivi debug](https://user-images.githubusercontent.com/7585083/99097835-2aee6f00-25a6-11eb-88eb-9a2e41f8703f.jpg)

**Comment by chrisbanes** [comment]
Thanks for the report. I'm actually in the process of re-writing those screens in Compose, so this shouldn't be an issue. 

See #729

**Comment by chrisbanes** [comment]
Closed with #729
