### ISSUE TITLE
[Question] Why is stateMutex.withLock { } needed?

### ISSUE THREAD

**Issue by lucamtudor** [chrisbanes/tivi#735]
@chrisbanes This might be a dumb question, but why it was necessary to use a mutex when updating the value of the MutableStateFlow?
https://github.com/chrisbanes/tivi/blob/12817a43ed3c239b75d77e23675fa8f7171c45cf/common-ui-view/src/main/java/app/tivi/ReduxViewModel.kt#L73

**Comment by chrisbanes** [comment]
This is to make sure that only 1 coroutine/thread is updating the value at a time.

**Comment by lucamtudor** [comment]
From the [StateFlow docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/), it seems the internal state machinery is thread-safe:

> **Concurrency**
All methods of state flow are thread-safe and can be safely invoked from concurrent coroutines without external synchronization.

Am I missing something?

**Comment by chrisbanes** [comment]
The issue isn't with `StateFlow`, it's with: `value = reducer(value)`

If multiple things try to read and set at the same time, some values will be overwritten.

**Comment by lucamtudor** [comment]
Somehow I completely missed the `reducer(state.value)` part 🤦‍♂️. Lesson learned, not checking new code at 2am next time.
Thanks!
