### ISSUE TITLE
UI - Follow/Unfollow FAB - the first letter of the text "Unfollow" is cut

### ISSUE THREAD

**Issue by SashaCube** [chrisbanes/tivi#738]
version 0.5.1

_steps to reproduce:_

1. Open any serial, that you haven't followed yet.
2. Without scrolling down press "Follow" FAB

![tivi_ui_bug](https://user-images.githubusercontent.com/32861062/100426345-6191b280-3099-11eb-9f8e-30fbe2430c96.jpg)

**Comment by chrisbanes** [comment]
Thanks for the report. This has already been reported in #701
