### ISSUE TITLE
Update readme section about Jetpack Compose

### ISSUE THREAD

**Issue by oas004** [chrisbanes/tivi#746]
The readme under Jetpack compose states that there are currently 3 pieces of UI written in compose. In the [Medium article: Jetpack Compose — Before and after](https://medium.com/androiddevelopers/jetpack-compose-before-and-after-8b43ba0b7d4f) it states that "Last week I removed AppCompat, Material Design Components, and other AndroidX widget libraries from the app, marking the point where Tivi’s UI is entirely Compose based.". This indicates that the project is now entirely in compose.

**Comment by chrisbanes** [comment]
Good catch, I'll update the README.
