### ISSUE TITLE
Suggested improvement for LazyListState handling in ShowDetails.kt

### ISSUE THREAD

**Issue by alexjlockwood** [chrisbanes/tivi#751]
Andrey actually randomly suggested this improvement to me the other day... and I noticed it could potentially be improved in Tivi as well.

In my case, Andrey suggested replacing one of my helper functions:

```
fun LazyListState.isScrolled() = firstVisibleItemIndex > 0 || firstVisibleItemScrollOffset > 0
```

with this:

```
@Composable
fun LazyListState.isScrolled(): Boolean {
    return remember(this) {
        derivedStateOf { firstVisibleItemIndex > 0 || firstVisibleItemScrollOffset > 0 }
    }.value
}
```

The reason being that it ensures you don't unnecessarily recompose the screen each time the first visible item index changes when the user is scrolling.

Anyways, I noticed this was an issue in the `ShowDetails.kt` composable here, so I guess that it could maybe be improved in the same way 🤷:

https://github.com/chrisbanes/tivi/blob/d2128c9792a645a23358acdf713d50f0adfc8a82/ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt#L174-L179

**Comment by alexjlockwood** [comment]
FWIW, I know this is kinda an iffy feature request... since I know you all are typically against polluting the API with helpers like this...  but I filed it anyway just in case cause this seems like something that would not be obvious to most developers: https://issuetracker.google.com/issues/174070148

**Comment by chrisbanes** [comment]
Going to close this, as I put this in the [Lists documentation](https://developer.android.com/jetpack/compose/lists#react-to-scroll-position)

**Comment by alexjlockwood** [comment]
Nice! Thanks for the link, gotta read this!
