### ISSUE TITLE
Moving Dependencies out of buildSrc...

### ISSUE THREAD

**Issue by Bradleycorn** [chrisbanes/tivi#757]
Hi @chrisbanes , I was wondering if you could elaborate a little bit on the decision to move dependency management out of the buildSrc directory?

**Comment by chrisbanes** [comment]
I was trying out dependabot.com, to see if it can update if the dependencies are listed in groovy (it can't). Aside from that, using `buildSrc` causes a build invalidation whenever it's content changes, so this is more optimal anyway.
