### ISSUE TITLE
Any reason to still use ThreeTen?

### ISSUE THREAD

**Issue by itsandreramon** [chrisbanes/tivi#762]
Why not use the official desugar support as described here: [Use Java 8 language features and APIs](https://developer.android.com/studio/write/java8-support)

**Comment by chrisbanes** [comment]
A few of my dependencies use it (`trakt-java`, `tmdb-java`), so there's not much point adding another copy in there.

**Comment by itsandreramon** [comment]
okay interesting, makes definitely sense!
