### ISSUE TITLE
Window insets after fragment change

### ISSUE THREAD

**Issue by AndrewKonst** [chrisbanes/tivi#773]
Window insets apply only after some time. At start (after fragment transaction) appbar layout below statusbar.  

https://user-images.githubusercontent.com/17138845/112455544-e13f3d80-8d6a-11eb-96e2-148426792cb1.mp4

Is there any solution to this behavior?

**Comment by chrisbanes** [comment]
This is due to https://github.com/google/accompanist/issues/155. There's no fix as yet, but it will go away once the app has moved away from Fragments.

**Comment by chrisbanes** [comment]
No longer an issue now that we've removed all fragments
