### ISSUE TITLE
Insert data to PagingData may not be notified

### ISSUE THREAD

**Issue by b95505017** [chrisbanes/tivi#774]
https://github.com/chrisbanes/tivi/blob/66461839635cb669c5dfbd0211e703a29c9e12b2/common-ui-compose/src/main/java/app/tivi/common/compose/paging/LazyPaging.kt#L102

If user swipe refresh at the top (index = 0), and there are new data loaded from top (e.g. `onInserted(position = 0, count = 1)`), old cached data from `currentlyUsedItems` would not update, because `onInserted/onRemoved` only update `_itemCount`.

**Comment by chrisbanes** [comment]
I've now removed my custom LazyPaging implementation, and gone back to the standard impl
