### ISSUE TITLE
Use gradle refreshVersions?

### ISSUE THREAD

**Issue by jmfayard** [chrisbanes/tivi#802]
Short story: if you are interested, I can submit a pull request to setup gradle refreshVersions in the project in order to make it easy to find available dependencies updates
https://jmfayard.github.io/refreshVersions/update-dependencies/

Longer story:

[gradle refreshVersions](https://jmfayard.github.io/refreshVersions/) is a Gradle plugin and my attempt at making managing dependencies faster and less error-prone. We just released a stable version 0.10.0

I'm trying on multiple oppen-source projects to make sure we are covering various use cases well.

What I found interesting in TiVi is that it's using versions catalogs, which is an interesting but currently rarely used feature. It overlaps with gradle refreshVersions - the adding dependency part - but can be combined with it as well and I'm interested to find out how well that works.

**Comment by chrisbanes** [comment]
> What I found interesting in TiVi is that it's using versions catalogs, which is an interesting but currently rarely used feature

Version catalogs was only added in Gradle 7.0, and is still marked as experimental (which is why it isn't very common right now). It is the official Gradle solution for dependency management going forward so I want to keep using it.

I'd happily accept a PR to start using `refreshVersions` for the updating side of things _if_ it works with version catalogs.

**Comment by jmfayard** [comment]
That's now done in https://github.com/chrisbanes/tivi/pull/803

Thank you, I better understand the use case now.

My only caveat is that writing the versions catalog file manually looks boring.
I think I will add a feature in refreshVersions to automatically generate the versions catalog file for Gradle 7 builds
