### ISSUE TITLE
Unused arguments in navigation

### ISSUE THREAD

**Issue by RedLabel1** [chrisbanes/tivi#807]
I'd like to ask why are you passing the `episodeId` argument to `EpisodeDetails` screen but then choose not to retrieve it when creating the `EpisodeDetails` composable.
```
private fun NavGraphBuilder.addEpisodeDetails(navController: NavController) {
    composable(
        route = LeafScreen.EpisodeDetails.route,
        arguments = listOf(
            navArgument("episodeId") { type = NavType.LongType }
        )
    ) {
        EpisodeDetails(
            navigateUp = {
                navController.popBackStack()
            },
        )
    }
}
```

**Comment by chrisbanes** [comment]
It's not unused, we read it from the SavedStateHandle in the ViewModel. It's a workaround for not being able to use Hilt assisted injection with Compose ATM.
