### ISSUE TITLE
Invalid injected android support version '202.7660.26.42.7351085', expected to be of the form 'w.x.y.z'

### ISSUE THREAD

**Issue by alwa** [chrisbanes/tivi#808]
Hi,

I get this error when attempting to sync the project (clone of main).
I can successfully build the project using command line (gradlew assembleDebug) but sync always fails.

I'm using Android Studio 4.2.1.

**Comment by chrisbanes** [comment]
The project currently depends on the Android Studio Arctic Fox Beta 1. I'll update the README.
