### ISSUE TITLE
Following list does not show last added item

### ISSUE THREAD

**Issue by henningBunk** [chrisbanes/tivi#815]
The last series I add is not shown on the 'following' page. I follow one show, the list is empty. The count inside the filter text box is correct though ("filter 1 show"). Than I follow another series and the the following list now shows the first series I added. Not the second though. And so on.

**Comment by chrisbanes** [comment]
This is likely to be a bug in the 'super sort' SQL query which I fixed in 541c050dc7742dafd067f14b35d12d9f7a72e67f
