### ISSUE TITLE
Clicking a series on the 'discover' page switches the bottom bar to 'watched'

### ISSUE THREAD

**Issue by henningBunk** [chrisbanes/tivi#816]
Sorry if this is the wanted behaviour. It just felt weird to me that when I click a series I havent watched in the discover page, the bottom bar selects 'Watched'. I think it should stay at 'Discover'.

**Comment by chrisbanes** [comment]
This should be fixed in 0.6.1. We had to start namespacing (prefixing) the nav routes for each top-level nav graph.
