### ISSUE TITLE
some shows are crashing the app

### ISSUE THREAD

**Issue by josevega96** [chrisbanes/tivi#823]
Adding some shows to collection  like Lucifer for example crashes app managed to get some logs hope they're helpful

> 
> -- 3 Jul 2021 20:50:34 ----
> 
> 07-03 20:48:45.600  1417  3136 I 

> ActivityTaskManager: START
> 
>  u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=app.tivi/.home.MainActivity bnds=[110,1321][921,1476]} from uid 10259
> 
> 07-03 20:48:45.642  1417  1480 I ActivityManager: Start proc 19952:app.tivi/u0a228 for pre-top-activity {app.tivi/app.tivi.home.MainActivity}
> 
> 07-03 20:48:45.656 19952 19952 E app.tivi: Not starting debugger since process cannot load the jdwp agent.
> 
> 07-03 20:48:45.659 19952 19952 W app.tivi: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
> 
> 07-03 20:48:45.691 19952 19952 W app.tivi: JIT profile information will not be recorded: profile file does not exist.
> 
> 07-03 20:48:45.726 19952 19976 W app.tivi: Unsupported class loader
> 
> 07-03 20:48:45.738 19952 19976 I app.tivi: The ClassLoaderContext is a special shared library.
> 
> 07-03 20:48:45.742 19952 19976 I app.tivi: The ClassLoaderContext is a special shared library.
> 
> 07-03 20:48:45.765 19952 19952 I TetheringManager: registerTetheringEventCallback:app.tivi
> 
> 07-03 20:48:45.816 19952 19991 I FA      :   adb shell setprop debug.firebase.analytics.app app.tivi
> 
> 07-03 20:48:45.920 19952 19952 W app.tivi: Accessing hidden method Landroid/content/res/Resources$Theme;->getKey()Landroid/content/res/Resources$ThemeKey; (greylist-max-o, reflection, denied)
> 
> 07-03 20:48:46.005  1417  1477 I ActivityTaskManager: Displayed app.tivi/.home.MainActivity: +401ms
> 
> 07-03 20:48:51.826 19952 19952 E AndroidRuntime: Process: app.tivi, PID: 19952
> 
> 07-03 20:48:51.830  1417  5292 W ActivityTaskManager:   Force finishing activity app.tivi/.home.MainActivity
> 
> 07-03 20:48:51.959  1417  5034 I WindowManager: WIN DEATH: Window{1ac7774 u0 app.tivi/app.tivi.home.MainActivity}
> 
> 07-03 20:48:51.959  1417  5292 I ActivityManager: Process app.tivi (pid 19952) has died: prcp TOP 
> 
> 07-03 20:48:51.959  1417  5034 W InputDispatcher: Attempted to unregister already unregistered input channel '1ac7774 app.tivi/app.tivi.home.MainActivity (server)'
> 
> 07-03 20:48:52.331  1417  1467 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f583da1 u0 app.tivi/.home.MainActivity t-1 f}}
> 
> ---- 3 Jul 2021 20:50:34 ----7-03 20:48:45.600  1417  3136 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=app.tivi/.home.MainActivity bnds=[110,1321][921,1476]} from uid 10259
> 
> 07-03 20:48:45.642  1417  1480 I ActivityManager: Start proc 19952:app.tivi/u0a228 for pre-top-activity {app.tivi/app.tivi.home.MainActivity}
> 
> 07-03 20:48:45.656 19952 19952 E app.tivi: Not starting debugger since process cannot load the jdwp agent.
> 
> 07-03 20:48:45.659 19952 19952 W app.tivi: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
> 
> 07-03 20:48:45.691 19952 19952 W app.tivi: JIT profile information will not be recorded: profile file does not exist.
> 
> 07-03 20:48:45.726 19952 19976 W app.tivi: Unsupported class loader
> 
> 07-03 20:48:45.738 19952 19976 I app.tivi: The ClassLoaderContext is a special shared library.
> 
> 07-03 20:48:45.742 19952 19976 I app.tivi: The ClassLoaderContext is a special shared library.
> 
> 07-03 20:48:45.765 19952 19952 I TetheringManager: registerTetheringEventCallback:app.tivi
> 
> 07-03 20:48:45.816 19952 19991 I FA      :   adb shell setprop debug.firebase.analytics.app app.tivi
> 
> 07-03 20:48:45.920 19952 19952 W app.tivi: Accessing hidden method Landroid/content/res/Resources$Theme;->getKey()Landroid/content/res/Resources$ThemeKey; (greylist-max-o, reflection, denied)
> 
> 07-03 20:48:46.005  1417  1477 I ActivityTaskManager: Displayed app.tivi/.home.MainActivity: +401ms
> 
> 07-03 20:48:51.826 19952 19952 E AndroidRuntime: Process: app.tivi, PID: 19952
> 
> 07-03 20:48:51.830  1417  5292 W ActivityTaskManager:   Force finishing activity app.tivi/.home.MainActivity
> 
> 07-03 20:48:51.959  1417  5034 I WindowManager: WIN DEATH: Window{1ac7774 u0 app.tivi/app.tivi.home.MainActivity}
> 
> 07-03 20:48:51.959  1417  5292 I ActivityManager: Process app.tivi (pid 19952) has died: prcp TOP 
> 
> 07-03 20:48:51.959  1417  5034 W InputDispatcher: Attempted to unregister already unregistered input channel '1ac7774 app.tivi/app.tivi.home.MainActivity (server)'
> 
> 07-03 20:48:52.331  1417  1467 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f583da1 u0 app.tivi/.home.MainActivity t-1 f}}
> 
> ---- 3 Jul 2021 20:50:34 ----

**Comment by wiryadev** [comment]
I try to follow Lucifer but i dont get the issue you have
![image](https://user-images.githubusercontent.com/26060382/124758591-ebbbc680-df58-11eb-8a07-d2bd9da25757.png)
![image](https://user-images.githubusercontent.com/26060382/124758608-f1191100-df58-11eb-8b10-a4044caa4610.png)
