### ISSUE TITLE
Android Support plugin error when running gradle sync on project

### ISSUE THREAD

**Issue by dturner** [chrisbanes/tivi#846]
After importing the project into Android Studio Arctic Fox I ran Gradle Sync and received the following error: 

```
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.
```

I'm assuming this is because I need the latest Canary version of Android Studio - BumbleBee 2021.1.1. 

If this is correct then the README should be updated to reflect this requirement.

**Comment by AndroidPat** [comment]
After using @solomaticydl solution I'm now facing a new error.

* Exception is:
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Invalid TOML catalog definition:
  - Problem: In version catalog libs, unknown top level elements [plugins].
    
    Reason: TOML file contains an unexpected top-level element.
    
    Possible solution: Make sure the top-level elements of your TOML file is one of 'bundles', 'libraries', 'metadata' or 'versions'.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/version_catalog_problems.html#toml_syntax_error for more details about this problem.

**Comment by 1ansam** [comment]
Same Issue like @AndroidPat. Give me help plz.

**Comment by kennir** [comment]
+1

**Comment by dodaithach** [comment]
A solution that works for me:
- Open the project in the latest [Android Studio Preview](https://developer.android.com/studio/preview).
- Change [android gradle plugin](https://github.com/chrisbanes/tivi/blob/main/gradle/libs.versions.toml#L35) to `7.1.0-alpha12`.

**Comment by matale** [comment]
I got it to build by using the current AS Beta version
```
Android Studio Bumblebee | 2021.1.1 Beta 1
Build #AI-211.7628.21.2111.7785763, built on October 1, 2021
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Statistic (4.1.7), org.jetbrains.kotlin (211-1.5.31-release-551-AS7442.40)
```

 Cannary doesnt work.

**Comment by brightchip** [comment]
I tried download the beta AS as well as changed the gradle version number but none of them work. 
How do you build the pure project successfully on a brand new installed Android Studio ?

**Comment by brightchip** [comment]
> After using @solomaticydl solution I'm now facing a new error.
> 
> * Exception is:
>   java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Invalid TOML catalog definition:
>   
>   * Problem: In version catalog libs, unknown top level elements [plugins].
>     Reason: TOML file contains an unexpected top-level element.
>     Possible solution: Make sure the top-level elements of your TOML file is one of 'bundles', 'libraries', 'metadata' or 'versions'.
>     Please refer to https://docs.gradle.org/7.0.2/userguide/version_catalog_problems.html#toml_syntax_error for more details about this problem.

Did you solve your errors ? Can you give me a hand
