### ISSUE TITLE
Back button and pressing the previous tab in bottom navigation does not show the same result?

### ISSUE THREAD

**Issue by TobiasEdqvist** [chrisbanes/tivi#894]
Hi!

Is navigation in compose really buggy? It seems like that different "stacks" are used depending on device/android back button or the tabs are used for navigation "back". 

Scenario;
1) Open app
2) Scroll on Discover and open a popular show (I used Game of Thrones)
3) Now with the show details open on Discover, switch tab to Search
4) While on Search, press Discover tab again. This will show the show details for the opened show.
5) Go back to Search again
6) While on Search, press back button on the phone (Samsung Galaxy S8)
7) Discover will now be selected again, however this time it shows "Being Watched Now" and "Popular" as if the tab was opened on first launch...
8) Press the already selected Discover tab, this will take the user to the previously opened show details...

**Comment by Veeksi** [comment]
I noticed the same issue! It would be cool to see, how this can be fixed cos I have faced this same issue on my own apps

**Comment by DanielJ06** [comment]
I'm facing the same issue 😔. Did you guys found a workaround?

**Comment by chrisbanes** [comment]
Closing this as the navigation stack has been rewritten since.
