### ISSUE TITLE
`suspend operator fun invoke` is not possible

### ISSUE THREAD

**Issue by mainrs** [chrisbanes/tivi#924]
Related to the comment here: https://github.com/chrisbanes/tivi/blob/bd61508e7411579deae6bb2a3d27cca354d14706/domain/src/main/java/app/tivi/domain/Interactor.kt?rgh-link-date=2022-07-10T22%3A08%3A53Z#L86-L94

I have a similar construct in one of my apps and using `suspend` together with the `invoke` operator works on my end. Kotlin 1.6.21 is what I use.

**Comment by chrisbanes** [comment]
I'm not sure why you've raised this as an issue?
