### ISSUE TITLE
How to run this code in AS Chipmunk?

### ISSUE THREAD

**Issue by AndroidDev100** [chrisbanes/tivi#932]
<img width="1440" alt="Screenshot 2022-07-28 at 2 54 43 PM" src="https://user-images.githubusercontent.com/60289054/181471331-9c289a2c-9cb3-4286-8f67-2eb79db4d938.png">

Screenshot is missing the app folder. pls suggest

**Comment by chrisbanes** [comment]
Yeah, you need to use Android Studio Dolphin (or newer) at the moment: https://github.com/chrisbanes/tivi/blob/main/README.md#development-setup
